server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json, application/xml,text/html,image/jpeg,image/png,text/css,application/javascript,video/mp4
    min-response-size: 2048
  servlet: 
    session:
      timeout: 3000s
      persistent: false
      cookie:
        http-only: true

spring.config.import: ncos.yml

spring:
  profiles:
    active: navy #lnsystemHmmLand #lnsystemNavy # \ud65c\uc131\ud654\uc2dc\ud0ac \ud504\ub85c\ud544
    group:
      navy: "navy"
      land: "land"
      hmmNavy: "hmmNavy"
      hmmLand: "hmmLand"

---

spring: 
  config: 
    activate: 
      on-profile: navy
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://thesys.biz:appendUrl
    #url: ENC(9vixZr3Y0U1u5Sw3ux7EP6hc+s3zXRes+B1RAps/nsWeyEZGxpNNM74DEem8yWGe)
    #url: jdbc:mariadb://localhost:3306/ncos
    #username: ENC(s/9zhfHSWVrLIuqyjGQ8Kg==)
    #password: ENC(Uz6jUJ5tezNSjJ+2AEFc6npsb+Ivt0gs)
    username: dbUser
    password: dbPwd
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1 FROM DUAL
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      location: /data/was/ncos/upload
      maxFileSize: 2048MB
      maxRequestSize: 4096MB

---

spring: 
  config: 
    activate: 
      on-profile: land
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:appendUrl
    #url: ENC(9vixZr3Y0U1u5Sw3ux7EP6hc+s3zXRes+B1RAps/nsWeyEZGxpNNM74DEem8yWGe)
    #url: jdbc:mariadb://192.168.210.16:3306/ncos
    #username: ENC(s/9zhfHSWVrLIuqyjGQ8Kg==)
    #password: ENC(Uz6jUJ5tezNSjJ+2AEFc6npsb+Ivt0gs)
    username: dbUser
    password: dbPwd
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1 FROM DUAL
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      location: /data/was/ncos/upload
      maxFileSize: 2048MB
      maxRequestSize: 4096MB

---

spring: 
  config: 
    activate: 
      on-profile: hmmLand
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:appendUrl
    #url: ENC(0KNEv4jLgVL9SfXm0Wvy3zI316OKE7m1hF1UdEaSpaMRPTxiYgsIaVh7+mDJ3hZ2)
    #username: ENC(s/9zhfHSWVrLIuqyjGQ8Kg==)
    #password: ENC(Uz6jUJ5tezNSjJ+2AEFc6npsb+Ivt0gs)
    username: dbUser
    password: dbPwd
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1 FROM DUAL
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      location: /data/was/ncos/upload
      maxFileSize: 2048MB
      maxRequestSize: 4096MB

---

spring: 
  config: 
    activate: 
      on-profile: hmmNavy
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:appendUrl
    #url: ENC(0KNEv4jLgVL9SfXm0Wvy3zI316OKE7m1hF1UdEaSpaMRPTxiYgsIaVh7+mDJ3hZ2)
    #username: ENC(s/9zhfHSWVrLIuqyjGQ8Kg==)
    #password: ENC(Uz6jUJ5tezNSjJ+2AEFc6npsb+Ivt0gs)
    username: dbUser
    password: dbPwd
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1 FROM DUAL
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      location: /data/was/ncos/upload
      maxFileSize: 2048MB
      maxRequestSize: 4096MB

---

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*
  cache:
    jcache:
      config: classpath:ehcache.xml
  
mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: mil.ln.ncos.cmmn,mil.ln.ncos.**.vo
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: "NULL"
      
logging:
  config: classpath:log4j2.yml
  
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    

    
#vm argument
#add last line in tomcat/conf/catalina.properties 
# if run eclipse then under params -D attatch
# -Djava.net.preferIPv4Stack=true
# -Djasypt.encryptor.password=1245
# ship : tcpClient or udpClient = true and others false
# land : tcpServer or udpServer = true and others false
# tcpServer=false
# udpServer=true
# tcpClient=false
# udpClient=false    